version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: pd-mcp-bridge
    IMAGE_TAG: latest
phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=$(aws configure get region || echo us-east-1)
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPO_URI:$IMAGE_TAG